# Generated by Django 4.2.20 on 2026-07-17 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('value', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('module', models.CharField(blank=True, default='', max_length=40)),
                ('captured_for', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
