# Generated by Django 4.2.20 on 2026-07-17 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voiceroom',
            options={'ordering': ['-is_live', '-participant_count', 'title']},
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='host_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='max_speakers',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='participant_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='password_hint',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='recording_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='voiceroom',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voiceroom',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('password', 'Password Protected'), ('invite', 'Invite Only'), ('scheduled', 'Scheduled')], default='public', max_length=40),
        ),
        migrations.CreateModel(
            name='RoomPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=240)),
                ('options', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='rooms.voiceroom')),
            ],
        ),
        migrations.CreateModel(
            name='RoomChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.voiceroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(choices=[('listener', 'Listener'), ('speaker', 'Speaker'), ('moderator', 'Moderator'), ('host', 'Host')], default='listener', max_length=20)),
                ('is_muted', models.BooleanField(default=True)),
                ('hand_raised', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.voiceroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
