# Generated by Django 4.2.20 on 2026-07-21 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'travel agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlightListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=120)),
                ('flight_number', models.CharField(blank=True, default='', max_length=40)),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('cabin_class', models.CharField(default='Economy', max_length=40)),
                ('stops', models.PositiveIntegerField(default=0)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='air.travelagency')),
            ],
            options={
                'ordering': ['departure_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('passenger_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('ticketed', 'Ticketed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='air.flightlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
