# Generated by Django 4.2.20 on 2026-07-17 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], default='in_app', max_length=40)),
                ('category', models.CharField(choices=[('system', 'System'), ('academy', 'Academy'), ('streaming', 'Streaming'), ('rooms', 'Rooms'), ('jobs', 'Jobs'), ('store', 'Store'), ('wallet', 'Wallet'), ('chat', 'Chat')], default='system', max_length=40)),
                ('action_url', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
