# Generated by Django 4.2.20 on 2026-07-16 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='stream',
            name='church_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stream',
            name='duration_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='playback_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stream',
            name='series',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stream',
            name='viewers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('scheduled', 'Scheduled'), ('recorded', 'Recorded'), ('ended', 'Ended')], default='scheduled', max_length=40),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='StreamChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='streaming.stream')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayers', to='streaming.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
