# Generated by Django 4.2.20 on 2026-07-17 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='language',
            field=models.CharField(default='en', max_length=16),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notify_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='key',
            field=models.CharField(blank=True, default='defaults', max_length=80),
        ),
    ]
