# Generated by Django 4.2.20 on 2026-07-17 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiostation',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='radiostation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='radiostation',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='radiostation',
            name='listeners',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiostation',
            name='presenters',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='radiostation',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('host', models.CharField(blank=True, default='', max_length=120)),
                ('duration_min', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='radio.radiostation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadioFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='radio.radiostation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'station')},
            },
        ),
    ]
