# Generated by Django 4.2.20 on 2026-08-02 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0002_coursecategory_institution_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['week_number', 'title']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-is_featured', 'name']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['week_number', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='academy.institution'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(default='on_track', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='institution',
            name='accent_color',
            field=models.CharField(blank=True, default='#DFA622', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='primary_color',
            field=models.CharField(blank=True, default='#100030', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='program_weeks',
            field=models.PositiveIntegerField(default=31),
        ),
        migrations.AddField(
            model_name='institution',
            name='student_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(blank=True, default='', max_length=120)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='academy.institution')),
            ],
            options={
                'verbose_name_plural': 'live classes',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio'), ('document', 'Document')], default='document', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academy.institution')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academy.institution')),
            ],
            options={
                'ordering': ['due_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AcademyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(blank=True, default='class', max_length=40)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academy.institution')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='academy.institution')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_students', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_mentors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('institution', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='draft', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academy.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AcademyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('instructor', 'Instructor'), ('staff', 'Staff'), ('academy_admin', 'Academy Administrator')], default='student', max_length=40)),
                ('current_week', models.PositiveIntegerField(default=1)),
                ('overall_progress', models.PositiveIntegerField(default=0)),
                ('attendance_pct', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='academy.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('institution', 'user')},
            },
        ),
    ]
