# Generated by Django 4.2.20 on 2026-07-17 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(choices=[('books', 'Books'), ('apparel', 'Apparel'), ('accessories', 'Accessories'), ('digital', 'Digital'), ('gift_card', 'Gift Card')], default='apparel', max_length=40)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
    ]
