# Generated by Django 4.2.20 on 2026-07-17 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('topup', 'Top Up'), ('withdrawal', 'Withdrawal'), ('purchase', 'Purchase'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('giving', 'Giving'), ('refund', 'Refund')], max_length=20)),
                ('amount_cents', models.IntegerField(default=0)),
                ('balance_after_cents', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('reference', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.walletaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
