# Generated by Django 4.2.20 on 2026-07-16 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('academy', 'Academy'), ('church', 'Church'), ('streaming', 'Streaming'), ('rooms', 'Rooms'), ('business', 'Business'), ('marketplace', 'Marketplace'), ('jobs', 'Jobs'), ('radio', 'Radio'), ('music', 'Music'), ('store', 'Store'), ('chat', 'Chat'), ('wallet', 'Wallet'), ('notifications', 'Notifications'), ('analytics', 'Analytics')], max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='circle', max_length=64)),
                ('requires_profile', models.BooleanField(default=False)),
                ('route', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('academy', 'Academy'), ('church', 'Church'), ('streaming', 'Streaming'), ('rooms', 'Rooms'), ('business', 'Business'), ('marketplace', 'Marketplace'), ('jobs', 'Jobs'), ('radio', 'Radio'), ('music', 'Music'), ('store', 'Store'), ('chat', 'Chat'), ('wallet', 'Wallet'), ('notifications', 'Notifications'), ('analytics', 'Analytics')], max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
