# Generated by Django 4.2.20 on 2026-07-16 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprofile',
            unique_together={('user', 'module')},
        ),
    ]
