# Generated by Django 4.2.20 on 2026-08-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledefinition',
            name='code',
            field=models.CharField(choices=[('streaming', 'Church Streaming'), ('academy', 'Rhema Academy'), ('learn', 'Rhema Learn'), ('radio', 'Live Radio'), ('business', 'Business Hub'), ('rooms', 'Rhema Rooms'), ('opportunities', 'Opportunities'), ('transport', 'Rhema-Transervices'), ('ticketing', 'Rhema-E-Ticketing'), ('air', 'RhemaAir')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='moduleprofile',
            name='module',
            field=models.CharField(choices=[('streaming', 'Church Streaming'), ('academy', 'Rhema Academy'), ('learn', 'Rhema Learn'), ('radio', 'Live Radio'), ('business', 'Business Hub'), ('rooms', 'Rhema Rooms'), ('opportunities', 'Opportunities'), ('transport', 'Rhema-Transervices'), ('ticketing', 'Rhema-E-Ticketing'), ('air', 'RhemaAir')], max_length=64),
        ),
    ]
